### ISSUE TITLE
why use negative values for lambda,...

### ISSUE THREAD

**Issue by caprone** [ja-thomas/autoxgboost#61]
HI
why use negative values for lambda, gamma and alpha ????

**Comment by caprone** [comment]
a ok, i cheked source;
`
autoxgbparset = makeParamSet(
  makeNumericParam("eta", lower = 0.01, upper = 0.2),
  makeNumericParam("gamma", lower = -7, upper = 6, trafo = function(x) 2^x),
  makeIntegerParam("max_depth", lower = 3, upper = 20),
  makeNumericParam("colsample_bytree", lower = 0.5, upper = 1),
  makeNumericParam("colsample_bylevel", lower = 0.5, upper = 1),
  makeNumericParam("lambda", lower = -10, upper = 10, trafo = function(x) 2^x),
  makeNumericParam("alpha", lower = -10, upper = 10, trafo = function(x) 2^x),
  makeNumericParam("subsample", lower = 0.5, upper = 1)
)
`
but, when i run the cntrl, seems that 'trafo' doesn't work, then it returned me negative values...for gamma, lambda e alpha..

**Comment by ja-thomas** [comment]
Hi,

these values are tuned on log-scale to make the tuning more efficient.
OptPath entries always use the values as seen by the optimizer, hence the untransformed values. 
The printer shows the correct transformed values and they are also saved in the `final.learner` object if you want to train the learner on new data (If you want to train it on the same data you can just use the `build.final.model` argument).

If you directly need the transformed values you can easily extract them from the `final.learner` with  `getHyperPars(res$final.learner)`.

I don't plan to change the internal representation of the `optim.result`, since it is done created by `mlrMBO` and not directly by autoxgboost.

Are the untransformed values returned anywhere else by autoxgboost, except for accessig them by `res$optim.result$x`?

**Comment by caprone** [comment]
a OK perfect, thanks;

@ja-thomas 
"Are the untransformed values returned anywhere else by autoxgboost, except for accessig them by res$optim.result$x?"

No, seems not

ps. Great work, very useful

**Comment by liuyanguu** [comment]
Very helpful. I spent quite some time to find the recommended parameters... Thanks for the discussion.

**Comment by ja-thomas** [comment]
cool :)
